### ISSUE TITLE
[Suggestion] Integrate into Pharo?

### ISSUE THREAD

**Issue by labordep** [olekscode/Containers-OrderedSet#2]
Hi @Ducasse, is this library included in Pharo?
It is possible to do that?

Because we are using a similar class in OpenSmock (developed a few years ago) and I think it would be cool to have that directly in Pharo :)

**Comment by Ducasse** [comment]
Hello

The idea is to remove things from Pharo not to add. So all the containers-OrderedSet are packages that are maintained, documented and tested that people can use in their project. 
But without bloating Pharo with them. 
The idea is to make sure that we can have a small kernel and that people can load only what they need.
If you want you can send your class and we can include it in this package. Like that it will make this package stronger.
S

**Comment by labordep** [comment]
Ok thanks Stephane, I will test this package :)
